import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/component/header";

const poppins = Poppins({
  variable: "--font-prime",
  subsets: ["latin"],
  weight:["300","400","500","600","700","800","900"]
});

const montserrat =  Montserrat({
  variable: "--font-mont",
  subsets: ["latin"],
    weight:["300","400","500","600","700","800","900"]

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>{children}</body>
    </html>
  );
}
